import React from "react";
import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import cx from 'classnames'
import AppLayout from "@/components/layout";
import { MantineProvider } from "@mantine/core";
import theme from "@/assets/theme";

// Styles
import "@mantine/core/styles.css";
import "@/assets/styles/styles.scss";

const montserrat = Montserrat({ weight: "400", subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang="en" className={cx(montserrat.className, poppins.className)}>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <AppLayout>{props.children}</AppLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
